### ISSUE TITLE
support 10.0.22621.4249

### ISSUE THREAD

**Issue by SunYuQii** [SniperThrilla/rdpwrap#1]
Hello! Can you update the ini file to support 10.0.22621.4249? Thank you very much!

**Comment by SniperThrilla** [comment]
Hello, I recommend using the rdpwrap.ini found at https://github.com/sebaxakerhtc/rdpwrap.ini

I was originally maintaining a rdpwrap.ini myself, but the people at that repository have been doing a great job at maintaining it. 10.0.22621.4249 is also supported with their one :)

As a sidenote, if you would like to use my one, you can use the offset finder utilities here that will help you add the necessary changes to your ini file to make it support any version.
